### PR TITLE
Add optional alternative quit key

### PR DESCRIPTION
**Pull request by PROGRAM-IX**
Third of three PRs based on svexican/cheeky#4, breaking it up into more granular chunks.

Lets user specify an alternative to Escape that will also close the switcher, in case the Escape key is inconvenient to reach.

- [x] Add `quit_key` option to switcher specifying another key which will quit the switcher (default: nil)
- [x] Update README to reflect this new option

(@svexican I wanted to include the Tab/Shift-Tab behaviour to scroll up and down in this PR, but I could not get Shift-Tab working no matter what I tried, so I left it out. If you have any tips on that front I'd love to hear them. None of the documentation seems to cover detecting a certain modkey in a keygrabber.)

### CODE REVIEW

**Comment by PROGRAM-IX** [comment]
Maybe I should add the Tab behaviour anyway, as it does loop around at least. What do you think?

**Comment by svexican** [comment]
Yes. Make that other pull request, please.

The `Shift + Tab` key is `ISO_Left_Tab`. Awful but true. Lets add it to the _upwards_ functionality. (loops as well)

**Comment by PROGRAM-IX** [comment]
That sounds terrible. So there was no need to mess around with the mod table at all? 

But cool, I'll make a PR to that effect as soon as I resolve conflicts here.

**Comment by PROGRAM-IX** [comment]
Resolved. Off to make the Tab/Shift-Tab pull request now.

**Pull request merged**
