### PR TITLE
Add Tab/Shift-Tab scrolling

### PR DESCRIPTION
**Pull request by PROGRAM-IX**
- [x] Add scrolling by Tab/Shift-Tab to the switcher
- [x] Update README to reflect this
- [x] Update README to explicitly mention scrolling as alternative to filtering

### CODE REVIEW

**Comment by PROGRAM-IX** [comment]
(Thanks to @svexican's comment https://github.com/svexican/cheeky/pull/7#issuecomment-215974875 I now know how Shift-Tab is represented in awesomewm.)

**Comment by PROGRAM-IX** [comment]
@svexican This has been an unexpectedly productive Saturday!

**Comment by svexican** [comment]
@PROGRAM-IX I should get out more! But for now: coding!

**Comment by PROGRAM-IX** [comment]
@svexican Thanks for working with me on these. :)

**Pull request merged**
